services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patients
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://db:27017/patients
      JWT_SECRET: STRONG_SECRET
      JWT_ACCESS_TOKEN_TTL: 3600
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongo_db_prod
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
