services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: patients_dev
    ports:
      - '3001:3000'
    environment:
      MONGO_URI: mongodb://mongo:27018/patients_dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongo_db_dev
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
